
    export class RandomSaying {

      private static vowels: string[] = ['a', 'e', 'i', 'o', 'u'];

        private static Animals: string[] = ['dog',
            'cat',
            'fish',
            'ox',
            'bear',
            "Pokemon",
            "Arctic hare",
            "Bat-eared fox",
            'Cheetah',
            'Chimpanzee',
            'Fairy penguin',
            'Jungle cat',
            'Pampa gray fox',
            'Platypus',
            'Blue Shark',
            'Warthog',
            'Yellow mongoose',
            'Aardvark',
            'Barn Owl',
            'Caterpillar',
            'Darwin\'s Frog',
            'Dolphin',
            'Unicorn',
            'Bearded Collie',
            'Oyster',
            'Millipede',
            'Otter',
            'Woolly Mammoth',
            'Wolverine',
            'Wombat',
            'Zebra',
            'Quail',
            'Skunk',
            'Shrimp',
            'Scallop',
            'Opossum',
            'Newt',
            'Llama',
            'Narwhal',
            'Gila monster',
            'Pikachu',
            'Celebi',
            'Eevee',
            'Snorlax',
            'Ditto',
            'Charizard',
            'Greninja',
            'Charmander',
            'Squirtle',
            'Rowlet',
            'Mewtwo',
            'Rockruff',
            'Pichu',
            'Gyarados',
            'Lucario',
            'Dragonite',
            'Raichu',
            'Bulbasaur',
            'Gengar',
            'Sylveon',
            'Zygarde',
            'Mew',
            'Garchomp',
            'Umbreon',
            'Gardevoir',
            'Jigglypuff',
            'Vikavolt',
            'Salamence',
            'Slowpoke',
            'Togepi',
            'Magikarp',
            'Lapras',
            'Espeon',
            'Growlithe',
            'Vulpix',
            'Rayquaza',
            'Tyranitar',
            'Metagross',
            'Blastoise',
            'Grubbin',
            'Milotic',
            'Arceus',
            'Marowak',
            'Arcanine',
            'Meowth',
            'Vaporeon',
            'Abra',
            'Munchlax',
            'Alakazam',
            'Muk',
            'Aardvark',
            'Addax',
            'Adelie Penguin',
            'African Elephant',
            'African Forest Elephant',
            'African Lions',
            'African Penguin',
            'African Spurred Tortoise',
            'African Wild Dog',
            'Africanized Bee',
            'Allen’s Swamp Monkey',
            'Alligator',
            'Allis Shad',
            'Alpine Ibex',
            'Amazonian Manatee',
            'American Oystercatcher Bird',
            'Anaconda Snake',
            'Ants',
            'Aquatic Warbler',
            'Arctic Wolf',
            'Armadillo',
            'Asian Elephant',
            'Asian Lion',
            'Atlantic Puffin',
            'Atlantic Spotted Dolphin',
            'Atlas Beetle',
            'Audubon’s Shearwater',
            'Australasian Grebe',
            'Australian Pelican',
            'Australian Swiftlet',
            'Bactrian Camels',
            'Badger',
            'Bean Goose',
            'Bee',
            'Beetle',
            'Bengal Tigers',
            'Big Eyed Squirrel Fish',
            'Bison',
            'Black Caimans',
            'Black House Spider',
            'Black Mamba Snake',
            'Black Necked Stilt',
            'Black Rhinoceros',
            'Black Widow Spider',
            'Blacktip Reef Shark',
            'Blacktip Shark',
            'Blister Beetle',
            'Blue and Yellow Macaw',
            'Blue Whale',
            'Blue-footed Booby Bird',
            'Boa Constrictor Snake',
            'Bottlenose Dolphin',
            'Bowhead Whale',
            'Brandling Worms',
            'Brazilian Wandering Spider',
            'British Mice',
            'British Moles',
            'British Water Vole',
            'British Wild Cats',
            'Broad-Snouted Caimans',
            'Brown Recluse Spider',
            'Brown Trout',
            'Bumble Bee',
            'Burying Beetle',
            'Butterfly',
            'Camels',
            'Campbell’s Dwarf Hamster',
            'Cape Gannet Bird',
            'Capercaillie',
            'Capuchin Monkey',
            'Capybara',
            'Caracal',
            'Cardinal Bird',
            'Caribbean Reef Shark',
            'Caribou',
            'Cats',
            'Centipede',
            'Cheetah',
            'Chickaree',
            'Chickens',
            'Chimpanzee',
            'Chinchilla',
            'Chinese Hamsters',
            'Chinstrap Penguin',
            'Chipmunk',
            'Christmas Beetle',
            'Cicada Killer Wasps',
            'Click Beetle',
            'Commerson Dolphin',
            'Common Buzzard',
            'Common Dolphin',
            'Common Frog',
            'Common Hippopotamus',
            'Common Kingfisher',
            'Common Lizard',
            'Common Newt',
            'Common Palm Civet',
            'Common Seal',
            'Common Toad',
            'Common Wasps',
            'Copperhead Snake',
            'Corncrake',
            'Cottonmouth Snake',
            'Cows',
            'Coyote',
            'Crab Plover',
            'Crabs',
            'Crocodile',
            'Cuban Solenodon',
            'Cuviers Dwarf Caimans',
            'Darkling Beetle',
            'De Brazza’s Monkey',
            'Deer',
            'Dingo',
            'Dog',
            'Dolphin',
            'Domestic Pig',
            'Dragonfly',
            'Dromedary Camels',
            'Duck-billed Platypus',
            'Ducks',
            'Dung Beetle',
            'Earthworms',
            'Eastern Lowland Gorilla',
            'Eastern Wolf',
            'Elephant Seal',
            'Elephants',
            'Elk',
            'Emperor Penguin',
            'Emu',
            'Erect-Crested Penguin',
            'Ethiopian Wolf',
            'Eurasian Water Shrew',
            'Eurasian Wolf',
            'Eurasian Wryneck',
            'European Hare',
            'European Otter',
            'False Black Widow Spider',
            'Fennec Fox',
            'Field Vole',
            'Fiji Blue Devil Damsel Fish',
            'Fiordland Crested Penguin',
            'Flatworms',
            'Fungus Beetle',
            'Funnel Web Spider',
            'Galapagos Barn Owls',
            'Galapagos Black Tipped Shark',
            'Galapagos Brown Noddy Tern',
            'Galapagos Brown Pelican Bird',
            'Galapagos Brydes Whale',
            'Galapagos Dark Billed Cuckoo',
            'Galapagos Dove',
            'Galapagos Eels',
            'Galapagos Fin Whale',
            'Galapagos Finche',
            'Galapagos Flamingo',
            'Galapagos Flightless Cormorant Sea Bird',
            'Galapagos Flycatcher Bird',
            'Galapagos Fur Seals',
            'Galapagos Gecko',
            'Galapagos Giant Tortoise',
            'Galapagos Great Blue Heron Bird',
            'Galapagos Great Frigate Bird',
            'Galapagos Green Sea Turtle',
            'Galapagos Hammerhead Shark',
            'Galapagos Hawk',
            'Galapagos Hoary Bat',
            'Galapagos Humpback Whale',
            'Galapagos Killer Whale',
            'Galapagos Land Iguana',
            'Galapagos Lava Gull Bird',
            'Galapagos Lava Heron Bird',
            'Galapagos Lava Lizard',
            'Galapagos Marine Iguana',
            'Galapagos Masked Booby Bird',
            'Galapagos Minke Whale',
            'Galapagos Mockingbird',
            'Galapagos Nazca Booby Bird',
            'Galapagos Penguin',
            'Galapagos Rail Bird',
            'Galapagos Rays',
            'Galapagos Red Bat',
            'Galapagos Red Billed Tropic Bird',
            'Galapagos Red Footed Booby Bird',
            'Galapagos Rice Rat',
            'Galapagos Sea Lions',
            'Galapagos Short Eared Owl',
            'Galapagos Short Finned Pilot Whale',
            'Galapagos Silky Shark',
            'Galapagos Smooth Billed Ani Bird',
            'Galapagos Snake',
            'Galapagos Sperm Whale',
            'Galapagos Storm Petrel Bird',
            'Galapagos Swallow Tailed Gull',
            'Galapagos Waved Albatross',
            'Galapagos Whale Shark',
            'Galapagos Whimbrel Bird',
            'Galapagos White Cheeked Pintail Duck',
            'Galapagos White Tipped Reef Shark',
            'Galapagos Willet Bird',
            'Galapagos Yellow Warbler Bird',
            'Galapagos Yellow-Crowned Night Heron',
            'Gemsbok',
            'Gentoo Penguin',
            'Gerenuk',
            'Gharial',
            'Giant Anteater',
            'Giant Panda Bear',
            'Giant Sable Antelope',
            'Giraffe',
            'Goats',
            'Gold, Silver and Blue Monkey',
            'Golden Eagle',
            'Golden Pheasant',
            'Gorilla',
            'Grasshopper',
            'Great Bittern',
            'Great Crested Newt',
            'Great Green Macaw',
            'Great White African Pelican Bird',
            'Great White Shark',
            'Greater Flamingo',
            'Greater Horseshoe Bat',
            'Greater Mouse-Eared Bat',
            'Greater Spot-Nosed Monkey',
            'Green Crabs',
            'Green Scarab Beetle',
            'Grevy’s Zebra',
            'Grey Jungle Fowl Bird',
            'Grey Loerie bird',
            'Grey Partridge',
            'Grey Seal',
            'Grey Wolf',
            'Grivet Monkey',
            'Grizzly Bear',
            'Ground Beetle',
            'Ground Centipede',
            'Guinea Pigs',
            'Hamerkop Bird',
            'Hamsters',
            'Harbour Porpoise',
            'Harp Seal',
            'Hazel Dormouse',
            'Hectors Dolphin',
            'Hedgehog',
            'Hermit Crabs',
            'Hippopotamus',
            'Hobo Spider',
            'Honey Bee',
            'Hoopoe Bird',
            'Hornets',
            'Horses',
            'Horseshoe Crab',
            'House Centipede',
            'Howler Monkey',
            'Humboldt Penguin',
            'Huntsman Spider',
            'Hydrozoan Jellyfish',
            'Ibisbill Bird',
            'Impala',
            'Indian Cuckoo Bird',
            'Indian Rhinoceros',
            'Indian Skimmer Bird',
            'Italian Wolf',
            'Jackal',
            'Jaguar',
            'Jambu Fruit Dove',
            'Japanese Spider Crab',
            'Javan Rhinoceros',
            'Jellyfish',
            'Katipo Spider',
            'Kea Parrot',
            'Kestrel Bird',
            'King Cobra Snake',
            'King Penguin',
            'Kinkajou',
            'Kittens',
            'Koala',
            'Komodo Dragon',
            'Ladybird',
            'Laughing Kookaburra',
            'Lemmings',
            'Lemur',
            'Lion',
            'Little Fairy Penguin',
            'Lizards',
            'Llama',
            'Long Horned Beetle',
            'Longhorn Cowfish',
            'Lynx',
            'Macaque Monkey',
            'Macaroni Penguin',
            'Magellanic Penguin',
            'Manatee',
            'Maned Wolf',
            'Manx Shearwater Bird',
            'Marine Angelfish',
            'Markhor',
            'Masai Giraffe',
            'Masked Finfoot Bird',
            'Mealy Parrot',
            'Meerkat',
            'Mexican Wolf',
            'Mice',
            'Military Macaw Parrot',
            'Milkweed Beetle',
            'Millipedes',
            'Monkey',
            'Moose',
            'Morpho Butterfly',
            'Moth',
            'Mountain Goat',
            'Mountain Gorilla',
            'Mountain Zebra',
            'Mouse Spider',
            'Mud Dauber Wasp',
            'Musk Ox',
            'Natterjack Toad',
            'New World Monkey',
            'New World Tarantula Spider',
            'Northern Short-tailed Shrew',
            'Nurse Shark',
            'Ocelot',
            'Okapi',
            'Old World Monkey',
            'Old World Tarantula Spider',
            'Opossums',
            'Orangutan',
            'Orb Weaver Spider',
            'Oryx',
            'Osprey',
            'Ostrich Bird',
            'Pantropical Spotted Dolphin',
            'Paper Wasp',
            'Parasitic Bee',
            'Peafowl Peacock',
            'Peccary',
            'Penguin',
            'Peruvian Fox',
            'Pigs',
            'Pine Marten',
            'Piranha Fish',
            'Plains Zebra',
            'Poison Arrow Frog',
            'Polar Bear',
            'Polecat',
            'Pollan Fish',
            'Porcupine',
            'Potter Wasp',
            'Praying Mantis',
            'Preuss’s Monkey',
            'Puma',
            'Pygmy Hippopotamus',
            'Quagga Zebra',
            'Quolls',
            'Rabbits',
            'Racoon',
            'Rainbow Bee Eater',
            'Ratel',
            'RattleSnake',
            'Red Back Jumping Spider',
            'Red British Squirrel',
            'Red Fox',
            'Red Kangaroo',
            'Red Kite',
            'Red Pandas',
            'Red Rock Crabs',
            'Red Wolf',
            'Red-backed Shrike',
            'Reticulated Giraffe',
            'Rhinoceros',
            'Rhinoceros Beetle',
            'Right Whales',
            'Risso’s Dolphin',
            'Roborovski Hamster',
            'Rockhopper Penguin',
            'Rough-Toothed Dolphin',
            'Royal Penguin',
            'Sacred Ibis Bird',
            'Saki Monkey',
            'Sally Lightfoot Crab',
            'Sand Lizard',
            'Scarlet Macaw',
            'Schneiders Dwarf Caiman',
            'Scottish Crossbill',
            'Sea Lion',
            'Sea Snake',
            'Seahorse',
            'Seals',
            'Secretary Bird',
            'Serval',
            'Shark',
            'Sheep',
            'Silvery Gibbon',
            'Six Eyed Sand Spider',
            'Skipper Butterfly',
            'Skylark',
            'Slender Loris',
            'Sloth',
            'Snake',
            'Snares Penguin',
            'Snow Leopard',
            'Snowshoe Hare',
            'Solitary Bee',
            'Song Thrush',
            'Southern Short-tailed Shrew',
            'Spectacled Bear',
            'Spectacled/Common Caiman',
            'Spider Monkey',
            'Spider',
            'Spinner Dolphin',
            'Spotted Beetle',
            'Squirrel Monkey',
            'St. Andrew’s Cross Spider',
            'Stag Beetle',
            'Stingless Bee',
            'Stink Bug',
            'Stoat',
            'Stone Curlew',
            'Stone Dwelling Centipede',
            'Striped Dolphin',
            'Striped Hyena',
            'Sugar Maple Borer Beetle',
            'Sumatran Rhinoceros',
            'Syrian Hamster',
            'Tamarin Monkey',
            'Tangle Web Spider',
            'Tapir',
            'Tarantula Spider',
            'Tawny Eagle',
            'Tawny Frogmouth',
            'Teira Batfish',
            'Thomson’s Gazelle',
            'Tiger Shark',
            'Titi Monkey',
            'Toco Toucan',
            'Tortoise',
            'Trapdoor Spider',
            'Tuatara',
            'Tundra Wolf',
            'Turtles',
            'Vampire Bats',
            'Vendace Fish',
            'Vulture',
            'Wallaby',
            'Wasps',
            'Water Beetle',
            'Weasel',
            'Weevil Beetle',
            'West African Manatee',
            'West Indian Manatee',
            'Western Lowland Gorilla',
            'Whales',
            'White Bengal Tiger',
            'White Rhino',
            'White Stork Bird',
            'White-clawed Crayfish',
            'Wild Boar',
            'Wild Rabbit',
            'Wildebeest',
            'Winter White Russian Hamster',
            'Wolf Spider',
            'Wolverine',
            'Wolves',
            'Wombat',
            'Worms',
            'Yacare Caimans',
            'Yellow jacket Wasp',
            'Yellow Sac Spider',
            'Yellow-eyed Penguin',
            'Zebras'];
        private static Compliments: string[] = ['smart',
            'strong',
            'cool',
            'fashionable',
            'stylish',
            'excellent',
            'nifty',
            'dandy',
            'boss',
            'marvelous',
            'majestic',
            'awesome',
            'briliant',
            'amazing',
            'fantastic',
            'adorable',
            'clever',
            'creative',
            'Breathtaking',
            'Bold',
            'Unique',
            'Spunky',
            'Charming',
            'Sparky',
            'silly'];
        private static Actions: string[] = ['climb',
            'skate',
            'float',
            'jump',
            'run',
            'fly',
            'sleep',
            'listen',
            'run',
            'walk',
            'jog',
            'bike',
            'skate',
            'turn',
            'twist',
            'shout',
            'jump',
            'laugh',
            'scream',
            'play',
            'swim',
            'color',
            'draw',
            'paint',
            'build',
            'create',
            'read',
            'write',
            'sing',
            'joke',
            'glue',
            'sharpen',
            'doodle',
            'leave',
            'enter',
            'exit',
            'wake up',
            'sleep',
            'skate',
            'eat',
            'drink',
            'dance',
            'taste',
            'sneeze',
            'cough',
            'skip',
            'ride'];
        private static Farewells: string[] = ['ADIOS!', 'BYE!', 'BYE-BYE!', 'FAREWELL!', 'GOODBYE!'];
        public static RandomFun(name: string = ''): string {
            let sayingNum = RandomSaying.random(0, 2);
            if (sayingNum == 0) {
                return RandomSaying.YouAreCompliment();
            }
            else {
                return RandomSaying.ActionCompliment();
            }
        }
        public static ActionCompliment(): string {
            var animal = RandomSaying.Animals[RandomSaying.random(0, RandomSaying.Animals.length)];
            let compliment = RandomSaying.Compliments[RandomSaying.random(0, RandomSaying.Compliments.length)];
            let connectingWord = 'a';
            if (RandomSaying.StartsWithVowel(compliment)) {
                connectingWord = 'an';
            }
            // tslint:disable-next-line:max-line-length
            return `You ${RandomSaying.Actions[RandomSaying.random(0, RandomSaying.Actions.length)]} like ${connectingWord} ${compliment} ${animal}`;
        }
        public static YouAreCompliment(): string {
            let animal = RandomSaying.Animals[RandomSaying.random(0, RandomSaying.Animals.length)];
            let connectingWord = 'a';
            if (RandomSaying.StartsWithVowel(animal)) {
                connectingWord = 'an';
            }
            // tslint:disable-next-line:max-line-length
            return `You are ${RandomSaying.Compliments[RandomSaying.random(0, RandomSaying.Compliments.length)]} like ${connectingWord} ${animal}`;
        }

        private static StartsWithVowel(s: string): boolean {
          if(s === null)
            {
              return false;
            }
          var text = s.toLocaleLowerCase();
          return RandomSaying.isVowel(text.charAt(0));
        }

        // tslint:disable-next-line:typedef-whitespace
        private static isVowel(x) : boolean {
              var result;
              result = x === 'a' || x === 'e' || x === 'i' || x === 'o' || x === 'o';
              return result;
          }

        private static random(startNum: number, endNum: number): number
        {
          return Math.floor((Math.random() * endNum - 1) + startNum);
        }
    }

